# Generated by Django 4.2 on 2024-02-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resturent", "0002_fooditem_menu_submenu_order_fooditem_submenu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="restaurant",
        ),
    ]
